version: 1.0.{build}
# Don't build when repository is tagged.
skip_tags: true
max_jobs: 1
image: Visual Studio 2019
clone_depth: 3

environment:
  OMP_NUM_THREADS: 4
  VENDOR_DIR: c:\projects\win32-vs16-tools
  # Add numdiff, ndselect to PATH
  # Add gfortran's runtime dll's to PATH
  PATH: c:\projects\win32-vs16-tools\bin;$(PATH);c:\msys64\mingw64\bin
  VCPKGDIR: C:\Tools\vcpkg
  GENERATOR: "Visual Studio 16 2019"
  CMAKE_OPTIONS: "-DCMAKE_TOOLCHAIN_FILE=%VENDOR_DIR%\\vs2019-toolchain.cmake" 
  #-DCMAKE_VERBOSE_MAKEFILE=ON"
  #QTDIR: c:\Qt\5.14.0
  #PATH+=c:\Qt\5.14.0\bin

  matrix:
    - BUILD_TYPE: Debug
      C4_OPTS: SCALAR

    - BUILD_TYPE: Debug
      C4_OPTS: MPI

    - BUILD_TYPE: Release
      C4_OPTS: MPI

# Notes: https://github.com/KineticTheory/Linux-HPC-Env/wiki/TPL-installs-via-vcpkg

install:
  # we start at $(APPVEYOR_BUILD_FOLDER) = c:\projects\draco-2th1a
  # Install MS-MPI
  - curl -L -o msmpisetup.exe https://download.microsoft.com/download/A/E/0/AE002626-9D9D-448D-8197-1EA510E297CE/msmpisetup.exe
  - msmpisetup.exe -unattend
  # - This zip file provides:
  #   . vcpkg port files for random123 and eospac.
  #   . prebuilt vcpkg installs of gsl openblas metis, msmpi, parmetis, eospac,
  #     and random123.
  #   . numdiff is in the 'bin' directory,
  #   . The vs2019-toolchain.cmake file used by this script.
  - cd \projects
  - curl -L -o win32-vs16-tools.zip https://github.com/KineticTheory/ci-demo/releases/download/vendors-201809/win32-vs16-tools.zip
  - 7z.exe -y x win32-vs16-tools.zip
  - xcopy %VENDOR_DIR%\ports\* %VCPKGDIR%\ports /E /Y /I /Q
  - xcopy %VENDOR_DIR%\installed\* %VCPKGDIR%\installed /E /Y /I /Q
  # After the above xcopy, all of these should be 'already installed'
  #- vcpkg --triplet x64-windows install gsl metis openblas msmpi parmetis random123 eospac
  - vcpkg list
  # Install some packages via chocolatey
  #- cinst doxygen.install
  #- cinst dia
  #- cinst graphviz
  # Fix a few issues
  - if EXIST "C:\Program Files\Git\usr\bin\sh.exe" ( del /F "C:\Program Files\Git\usr\bin\sh.exe" )
  # Fix bugs in cmake-3.16.2
  - xcopy %VENDOR_DIR%\cmake\* "C:\Program Files (x86)\CMake\share\cmake-3.16\Modules\Platform" /E /Y /I /Q

matrix:
  fast_finish: true

build_script:
  - cd \projects
  - mkdir build
  - cd build
# no MPI installed so force scalar builds.
  - echo cmake -G "%GENERATOR%" -A x64 %CMAKE_OPTIONS% -DDRACO_C4=%C4_OPTS% %APPVEYOR_BUILD_FOLDER%
  - cmake -G "%GENERATOR%" -A x64 %CMAKE_OPTIONS% -DDRACO_C4=%C4_OPTS% %APPVEYOR_BUILD_FOLDER%
  - echo cmake --build . --config %BUILD_TYPE% -j %NUMBER_OF_PROCESSORS%
  - cmake --build . --config %BUILD_TYPE% -j %NUMBER_OF_PROCESSORS%
  - echo ctest -C %BUILD_TYPE% -j 2 --output-on-failure
  - ctest -C %BUILD_TYPE% -j %NUMBER_OF_PROCESSORS% --output-on-failure

#build:
#  verbosity: minimal

# Environment

# 7zip="C:\Program Files\7-Zip\7z.exe"
# ALLUSERSPROFILE=C:\ProgramData
# ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk
# ANDROID_NDK_HOME=C:\Microsoft\AndroidNDK64\android-ndk-r16b
# ANDROID_NDK_PATH=C:\Microsoft\AndroidNDK64\android-ndk-r16b
# APPDATA=C:\Users\appveyor\AppData\Roaming
# APPVEYOR=True
# APPVEYOR_ACCOUNT_NAME=KineticTheory
# APPVEYOR_API_URL=http://localhost:50076/
# APPVEYOR_BUILD_AGENT_HYPERV_NIC_CONFIGURED=true
# APPVEYOR_BUILD_FOLDER=C:\projects\ci-demo
# APPVEYOR_BUILD_ID=30210013
# APPVEYOR_BUILD_NUMBER=81
# APPVEYOR_BUILD_VERSION=1.0.81
# APPVEYOR_BUILD_WORKER_IMAGE=Visual Studio 2019
# APPVEYOR_JOB_ID=31v991hi3ce9s0ya
# APPVEYOR_JOB_NUMBER=1
# APPVEYOR_PROJECT_ID=463591
# APPVEYOR_PROJECT_NAME=ci-demo
# APPVEYOR_PROJECT_SLUG=ci-demo
# APPVEYOR_REPO_BRANCH=new2020
# APPVEYOR_REPO_COMMIT=80b5cbdb27cec8dba59491ad5cb5868932fd767e
# APPVEYOR_REPO_COMMIT_AUTHOR=Kelly (KT) Thompson
# APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL=kgt@lanl.gov
# APPVEYOR_REPO_COMMIT_MESSAGE=Coordinate VS version with appveyor image.
# APPVEYOR_REPO_COMMIT_TIMESTAMP=2020-01-19T00:55:11.0000000Z
# APPVEYOR_REPO_NAME=KineticTheory/ci-demo
# APPVEYOR_REPO_PROVIDER=gitHub
# APPVEYOR_REPO_SCM=git
# APPVEYOR_REPO_TAG=false
# APPVEYOR_URL=https://ci.appveyor.com
# APR_ICONV_PATH=C:\Program Files (x86)\Subversion\iconv
# AVVM_DOWNLOAD_URL=https://appveyordownloads.blob.core.windows.net/avvm
# ChocolateyInstall=C:\ProgramData\chocolatey
# ChocolateyLastPathUpdate=132237683008423528
# CI=True
# CI_LINUX=False
# CI_WINDOWS=True
# CMAKE_PREFIX_PATH=c:\projects\vendors\gsl-2.5;c:\projects\vendors\lapack-3.8.0;c:\projects\vendors\metis-5.1.0
# CommonProgramFiles=C:\Program Files\Common Files
# CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
# CommonProgramW6432=C:\Program Files\Common Files
# COMPUTERNAME=APPVEYOR-VM
# ComSpec=C:\Windows\system32\cmd.exe
# DriverData=C:\Windows\System32\Drivers\DriverData
# DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK\
# EnableNuGetPackageRestore=true
# ERLANG_HOME=C:\Program Files\erl9.2
# GIT_LFS_PATH=C:\Program Files\Git LFS
# GOROOT=C:\go
# HOMEDRIVE=C:
# HOMEPATH=\Users\appveyor
# JAVA_HOME=C:\Progra~1\Java\jdk1.8.0
# lastexitcode=0
# LOCALAPPDATA=C:\Users\appveyor\AppData\Local
# LOGONSERVER=\\APPVEYOR-VM
# M2_HOME=C:\Program Files (x86)\Apache\Maven
# MAVEN_HOME=C:\Program Files (x86)\Apache\Maven
# MSYS2_PATH_TYPE=inherit
# NUMBER_OF_PROCESSORS=2
# OMP_NUM_THREADS=4
# OPENSSL_CONF=C:\OpenSSL-Win32\bin\openssl.cfg
# OS=Windows_NT
# Path=c:\projects\vendors\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\Git\cmd;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PowerShell\6\;C:\Program Files\7-Zip;C:\Program Files\Microsoft\Web Platform Installer\;C:\Tools\NuGet;C:\Tools\PsTools;C:\Program Files\Git\usr\bin;C:\Program Files\Git LFS;C:\Program Files\Mercurial\;C:\Program Files (x86)\Subversion\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin;C:\Tools\xUnit;C:\Tools\xUnit20;C:\Tools\NUnit\bin;C:\Tools\NUnit3;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform;C:\Program Files (x86)\nodejs\;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files (x86)\Yarn\bin\;C:\Ruby193\bin;C:\Python27;C:\Python27\Scripts;C:\go\bin;C:\Program Files (x86)\CMake\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Amazon\AWSCLI\;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\erl9.2\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft DirectX SDK;C:\Tools\WebDriver;C:\Program Files\LLVM\bin;C:\Tools\vcpkg;C:\Tools\Coverity\bin;C:\Program Files (x86)\NSIS;C:\Tools\Octopus;C:\Program Files\Meson\;C:\Program Files\Java\jdk1.8.0\bin;C:\Program Files (x86)\Apache\Maven\bin;C:\Tools\GitVersion;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps;C:\Users\appveyor\.dotnet\tools;C:\Users\appveyor\AppData\Roaming\npm;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Program Files\AppVeyor\BuildAgent\
# PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.CPL
# PROCESSOR_ARCHITECTURE=AMD64
# PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
# PROCESSOR_LEVEL=6
# PROCESSOR_REVISION=3f02
# ProgramData=C:\ProgramData
# ProgramFiles=C:\Program Files
# ProgramFiles(x86)=C:\Program Files (x86)
# ProgramW6432=C:\Program Files
# PROMPT=$P$G
# PSModulePath=C:\Users\appveyor\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Users\appveyor\Documents\WindowsPowerShell\Modules;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\PowerShell;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\;C:\Program Files\AppVeyor\BuildAgent\Modules
# PUBLIC=C:\Users\Public
# RANDOM123_INC_DIR=c:\projects\vendors\Random123-1.08\include
# SESSIONNAME=Console
# SystemDrive=C:
# SystemRoot=C:\Windows
# TEMP=C:\Users\appveyor\AppData\Local\Temp\1
# TMP=C:\Users\appveyor\AppData\Local\Temp\1
# USERDOMAIN=APPVEYOR-VM
# USERDOMAIN_ROAMINGPROFILE=APPVEYOR-VM
# USERNAME=appveyor
# USERPROFILE=C:\Users\appveyor
# VENDOR_DIR=c:\projects\vendors
# VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
# windir=C:\Windows
# WIX=C:\Program Files (x86)\WiX Toolset v3.11\
# xunit20=C:\Tools\xUnit20
#
